// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "testSwiftPlayground",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "testSwiftPlayground",
            targets: ["AppModule"],
            bundleIdentifier: "com.bhavinp.testSwiftPlayground",
            teamIdentifier: "6VRG2CGHH5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .boat),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .actionGames
        )
    ],
    dependencies: [
        .package(url: "https://github.com/BhavinPat/testPackage.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "testPackage", package: "testpackage")
            ],
            path: "."
        )
    ]
)